### ISSUE TITLE
Field slider should inherit parent block if shadow

### ISSUE THREAD

**Issue by samelhusseini** [RaspberryPiFoundation/blockly-samples#252]
**Category**

Plugins

**Component**

field-slider

**Describe the bug**

The slider field should inherit the parent block colour if it's a shadow block. 

**To Reproduce**
<img width="217" alt="Screen Shot 2020-05-01 at 11 26 59 AM" src="https://user-images.githubusercontent.com/16690124/80830994-d6058100-8b9e-11ea-9a4f-e90e9baec798.png">

**Expected behavior**

The slider colour should be the same as the parent. 
Order of precedence should favour the parent block's color if it's a shadow block.

**Screenshots**

See above

**Additional context**

To work on this issue, first read the [background information](https://developers.google.com/blockly/guides/contribute/samples) about how to contribute to samples and verify your changes.

The slider field sets its color in the `showEditor_` function. Currently, it only checks the source block's color, but if the source block is a shadow block, this fails as shown above. To fix this, do the following steps:

1. Run `npm run start` in the field-slider plugin directory to start the playground.
2. In the right-hand configuration settings panel.
3. Drag one of the "parent" blocks out of the toolbox and click the number to open the slider field. Note how the colors are inconsistent.
4. Change the slider field's `showEditor_` function to take into account if the block is a shadow block. You can check if it is with `this.sourceBlock_.isShadow()`. If it is a shadow block, then instead of setting the color to the source block's color, set it to the parent block's color. You can get the parent's block color with `this.sourceBlock_.getParent().getColour()`.
5. Test your changes by repeating step 3 and ensuring the colors match now.

For more information about shadow blocks, see [this page](https://developers.google.com/blockly/guides/configure/web/toolbox?hl=en#shadow_blocks)

**Comment by BeksOmega** [comment]
I'm not sure that we actually want to do this, because it only applies to zelos. The dropdown field [handles this by using a special constant](https://github.com/google/blockly/blob/da8e486995df8f0b7b08a086ffb1b4bd22b21963/core/field_dropdown.js#L288) in the [zelos renderer sets to true](https://github.com/google/blockly/blob/da8e486995df8f0b7b08a086ffb1b4bd22b21963/core/renderers/zelos/constants.js#L292). We could use the same flag to trigger the functionality in the slider field, but it sucks that the constant is prefixed with `FIELD_DROPDOWN`, and not something more generic.

**Comment by maribethb** [comment]
This happens in all the renderers, not just Zelos, because all the renderers use the block's color as the background for the slider div. So in this case there is no need to use the `FIELD_DROPDOWN_COLOURED_DIV` value. We could have chosen to do so in the beginning if we wanted the slider to be white in thrasos and colorful in zelos, to match the dropdown field, but that would be a behavior change since currently it always has a colored background.

**Comment by BeksOmega** [comment]
I think what I was concerned about is that in other renderers, the shadow block (and its color) are actually shown. So I think it makes sense to make the dropdown div the color of the shadow block in those cases:
![Screenshot 2022-08-18 2 39 08 PM](https://user-images.githubusercontent.com/25440652/185500260-cccef1ec-5f7c-4962-8ba3-56d84b35e819.png)

As opposed to zelos, which does not show the shadow block if the only element of the block is the field:
![Screenshot 2022-08-18 2 39 20 PM](https://user-images.githubusercontent.com/25440652/185500287-b1155f75-f98e-46f6-a3f7-e6c5e761e67d.png)

Where it definitely does make sense to use the color of the parent block.

I guess the question is whether you think it makes sense in the first case for the background of the slider to be green or not.

**Comment by maribethb** [comment]
Huh. Since most of the shadow blocks are numbers I never noticed they have their own colors haha. I thought they were all gray...

In that case, I think you're right that we shouldn't change this. In Zelos you cannot tell the difference between a shadow block and a real block visually, so the shadow block should behave the same as the real block IMO. If it would be blue when you drop a real block in, it should probably be blue before that as well. That seems least surprising.

The original screenshot looks incorrect, but it would be the exact same behavior if the slider block is a "real" block instead of  a shadow, so I think that's more of a problem with zelos in general than this specific behavior.

wdyt? i'm fine to just close this if you agree.

**Comment by BeksOmega** [comment]
Agree, closing.
