### ISSUE TITLE
Shift-drag to select multiple blocks and allow moving multiple block group

### ISSUE THREAD

**Issue by AnmAtAnm** [RaspberryPiFoundation/blockly-samples#267]
Several times I've found myself wanting to move multiple block groups at once when organizing my workspace (perhaps to make room for a new block group).  My instinctive action is to attempt to drag a rectangle around the blocks, but this just drags the workspace.

I suggest we allow user to hold shift to change the drag behavior into creating a rectangular selection marquee.

This might be the default behavior on non-scrollable workspaces.

**Comment by rachel-fenichel** [comment]
I just transferred this issue from Blockly to blockly-samples.  This is a good candidate for a plugin, because it is behaviour that we think is interesting but not a good fit for core Blockly. 

This would be a workspace plugin, so its name would be `@blockly/workspace-multi-select`.

It's now in the [discussion phase](https://github.com/google/blockly-samples/wiki/Adding-A-Plugin#discussion) and open for conversation. The first two points to discuss are:
- desired behaviour
- APIs needed in core Blockly

@amber-cd @asanzo @AnmAtAnm

**Comment by asanzo** [comment]
How very exciting it is to see this one moving around. Thanks, Rachel! :mechanical_arm: 

I've updated a bit my previous comment. I still think amber-cd has some great ideas here. I imagined the behaviour with and without value inputs and statement inputs and I think what amber-cd says works as expected.

**Comment by amber-cd** [comment]
Regarding @asanzo's points:

* The change to 2. is equally logical and I'm fine with it
* I think that holding shift to select the first and last block in a stack in order to select all blocks between them is logical, but I'd want a way to indicate that I do want to select only these blocks and not the blocks between them (such as holding ctrl + shift).

I agree that the touchscreen problem would need to be addressed... I'd say that could be addressed either by drawing a rectangle and automatically selecting all blocks within it or by adding some type of "selection mode" toggle button which would change selection behavior on touchscreens between single and multiple.

**Comment by BeksOmega** [comment]
Recent requests from App Inventor and [Sandspiel Studio](https://groups.google.com/g/blockly/c/A9DB5Z0VXEs/m/Xns0L50JBQAJ)

**Comment by HollowMan6** [comment]
> Recent requests from App Inventor and [Sandspiel Studio](https://groups.google.com/g/blockly/c/A9DB5Z0VXEs/m/Xns0L50JBQAJ)

Hi everyone, glad to have a chance to implement this issue during my [Google Summer of Code 2022](https://summerofcode.withgoogle.com/programs/2022/projects/9wF06HWE) at [MIT App Inventor](https://github.com/mit-cml). Now an initial demo for this has already been worked out by myself. You can find the PR at https://github.com/mit-cml/workspace-multiselect/pull/1 .

The user behavior of the plugin mainly follows @amber-cd 's [idea](https://github.com/google/blockly-samples/issues/267#issuecomment-464184902) , with modifications that are more practical to implement. You can check in detail at the PR description.

It would be great if you could provide any suggestions of the user behavior/bugs you encounter or any other general feedback to help improve the plugin. Thanks in advance!

**Comment by HollowMan6** [comment]
Now the plugin has already been published to [NPM](https://www.npmjs.com/package/@mit-app-inventor/blockly-plugin-workspace-multiselect). You can also find the demo and blog post here: https://groups.google.com/g/blockly/c/1qb-M8HZYzY

**Comment by gonfunko** [comment]
Closing this out now that the plugin created by @HollowMan6 is available.
