### ISSUE TITLE
Can i use color slider for LED?

### ISSUE THREAD

**Issue by shycoded** [RaspberryPiFoundation/blockly-samples#356]
Hi guys I'm new to here and i'm not good at English. 

 I wanna choose LED color with color slider but i can't find the way to do that.

I found Scratch 3.0 has the function that i want but i don't know how to apply it to the blockly.
![Untitled](https://user-images.githubusercontent.com/69042796/92757747-ff45e180-f3c8-11ea-833b-1e0f314a63d6.png)

I found that there's no field_colour_slider.js in blockly/core/ so i paste it from scratch but it doesn't work. I hope someone helping me. thank you

**Comment by shycoded** [comment]
Yeah, the link that you gave me is really good document and it can help me but i'm not good at coding and it is little bit hard for me. I guess dropDownDiv is similar to slider right?

**Comment by pakya-1909** [comment]
Hii !!  I wanted to work on this issue. If any one is not working on it please assign to me.

**Comment by johnnesky** [comment]
Hello! It's been 2 years since there has been any activity on this issue, but I'm interested in working on making a plugin for color slider fields.

I think, if desired, I can recreate the three hue/saturation/brightness sliders as demonstrated by Scratch. 

I don't think I can recreate the eyedropper tool as-is. Even Scratch's eyedropper only supports taking color values from Scratch's stage, limiting its utility. 

However, HTML has a built-in color input widget: ```<input type="color"/>```. When clicked, this widget pops up its own color selection dropdown menu. Different browsers provide different color editors in this dropdown (e.g. Chrome provides a hue slider and saturation/brightness field, Safari provides swatches), but they generally include an eyedropper option that supports taking colors from anywhere on the screen. 

I propose building a plugin that adds a new field type called FieldColourSlider or "field_colour_slider" that, when clicked, displays a custom dropdown with the HSV sliders along with a button to activate the browser's built-in color editor.

**Comment by johnnesky** [comment]
Correction: there IS a standalone eyedropper feature that can sample anywhere on the screen, activated by JavaScript: https://developer.mozilla.org/en-US/docs/Web/API/EyeDropper

However, it is only available in some browsers (desktop chrome/edge/opera) so I may try to use it but I'll still have to fall back to the browser color picker.

**Comment by rachel-fenichel** [comment]
The Scratch colour slider is implemented [here](https://github.com/LLK/scratch-blocks/blob/develop/core/field_colour_slider.js).
