### ISSUE TITLE
Blocks can go under the flyout

### ISSUE THREAD

**Issue by alschmiedt** [RaspberryPiFoundation/blockly-samples#592]
**Category**
plugins

**Component**
Continuous Toolbox

**Describe the bug**

**To Reproduce**

1. Go to 'https://google.github.io/blockly-samples/plugins/continuous-toolbox/test/
2. Pull out a "count with j from 1 to 10 by 1 block"
3. Scroll the workspace over so the block goes under the flyout.

**Expected behavior**
The block should not be able to go under the flyout.

**Screenshots**
<img width="1057" alt="Screen Shot 2021-03-12 at 3 24 24 PM" src="https://user-images.githubusercontent.com/23059043/111008922-139e7300-8347-11eb-9e92-53a4a4c6a2bf.png">

**Additional context**
This only seems to happen if the content area is above a certain size.

**Comment by moniika** [comment]
It is not a bug for blocks to show under the flyout when the workspace is scrolled horizontally. This is consistent with the behavior of the simple and default category flyout.

If a developer desires blocks to not go under the flyout, then the developer can set the workspace to vertical-only scroll.

Alternatively, if the desire is to prevent blocks from showing, rather than from going under, the Flyout can be styling using CSS by setting the fill-opacity of `.blocklyFlyoutBackground` to 1.
