### ISSUE TITLE
Failed to load config "react-app" to extend from blockly-samples/examples/blockly-react/package.json

### ISSUE THREAD

**Issue by suiato** [RaspberryPiFoundation/blockly-samples#715]
**Category**
 - Examples

**Component**
react-app

**Describe the bug**
Runnng npm run deploy,

> Failed to load config "react-app" to extend from.
> Referenced from: /home/suiato/git/blockly-samples/examples/blockly-react/package.json
> lerna ERR! npm run predeploy exited 1 in 'blockly-react-sample'

**To Reproduce**
1. Go to 'blockly-samples'
2. Run 'npm run deploy'

**Expected behavior**
No error.

**Comment by maribethb** [comment]
Could you provide a little more information about what you're trying to do? `npm run deploy` is for deploying all of the demos to a GitHub pages site. In other words, deploy [this site](https://google.github.io/blockly-samples/) on your own GitHub pages site. Is that what you're intending to do? If so, there are prerequisites for running this command, e.g. you need to run `npm install` for plugins and examples. This sounds like an error from not installing the dependencies for the react example. There are instructions for deploying the site in the [gh-pages branch readme](https://github.com/google/blockly-samples/tree/master/gh-pages#to-personal-gh-pages). Those instructions will tell you the prerequisite steps for the deploy command.

If instead, you want to run the react example, you would run `npm run start` in the directory for that example.

**Comment by suiato** [comment]
@maribethb
thank you for your detailed explanation and instructions. I'm a newbie here, and will learn more before trying to "deploy". Luckily, I've succeeded in running many of the samples ([here](http://blockly-samples.aiwill.work/)), and will be able to try to customize them.
My current objective is to extend blockly to p5.js. The repo [blockp5.js](https://github.com/ycatch/blockp5.js/blob/master/README.ja.md) worked fine (like [here](http://blockp5js.aiwill.work/)), but has been inactive for 3 years. Any other attempts in this direction? I'll appreciate information on the subject.

**Comment by maribethb** [comment]
No problem, and welcome to Blockly! 

Abby just told me about a project called Rigglin that uses Blockly with p5: https://medium.com/@jtnimoy/introducing-rigglin-b849eca30cb6 . There might be others as well. This would be a great question for the developer forum: https://groups.google.com/g/blockly where other Blockly users might be more likely to see your question and chime in if they're also using p5.

I'm going to close this issue since it doesn't seem like there is a bug here, but please do follow up on the forum if you have additional questions about how to use Blockly :)
