### ISSUE TITLE
react-blockly

### ISSUE THREAD

**Issue by pelikhan** [RaspberryPiFoundation/blockly-samples#725]
Is there a plan to ship a NPM package for react-blockly?

**Comment by alschmiedt** [comment]
There is a [react-blockly](https://www.npmjs.com/package/react-blockly) npm package that is supported by an external contributor. I don't think we have any plans to release a package internally. 

I'm going to close, since this is more a question rather than a feature request. But if I misunderstood or you have more questions feel free to leave a comment and I can reopen.

**Comment by pelikhan** [comment]
I am using the react-blockly package and it's pretty good. I'll upstream fixes in there. Thanks for the answer.
