### ISSUE TITLE
Lint errors should cause github actions to fail

### ISSUE THREAD

**Issue by alschmiedt** [RaspberryPiFoundation/blockly-samples#816]
**Category**

Plugins
**Component**
dev-scripts

**Is your feature request related to a problem? Please describe.**
In our last release of blockly samples we found out that lint errors were causing our packages to be published without a dist folder. 

**Describe the solution you'd like**
When someone submits a PR with lint errors the errors are displayed in the file diff, but ci does not fail. We would rather ci fail so we can keep linting errors out of master.

**Describe alternatives you've considered**

**Additional context**
See #818 for more information on why this is necessary.

**Comment by maribethb** [comment]
I've been looking into doing this but finding it difficult due to the way we have lerna set up. 

The command should exit with a non-0 exit code to make GitHub show it as failed. (Though we probably only want to do that in a CI environment so that it doesn't block publishing.)

eslint is run separately for each package using lerna, so if I set the exit code for one package, lerna will fail early and not run lint on every package (undesirable). There is a `--no-bail` option but when I use it then lerna uses exit code 0 regardless of the exit code of any of the sub-commands. I'm not sure how else to accomplish this using lerna.

It might be easier if we didn't use lerna for this task at all and just linted at the root level. However ideally we would also still be able to lint one individual package. Not sure how easy it would be to set this up but this might be the next thing I try. Check out this comment from a lerna maintainer for support of this approach :) `https://github.com/lerna/lerna/issues/2044#issuecomment-484164341`

**Comment by alschmiedt** [comment]
> The command should exit with a non-0 exit code to make GitHub show it as failed. (Though we probably only want to do that in a CI environment so that it doesn't block publishing.)

I think we actually do want this to block publishing because of the dist problem described above. I also think it won't matter that much if it fails for publishing if everything that goes in here is correct.

> eslint is run separately for each package using lerna, so if I set the exit code for one package, lerna will fail early and not run lint on every package (undesirable

Could we do something similar to the tests? Where we go through each one and then at the end exit based on whether we have any failures?

**Comment by maribethb** [comment]
Some random notes from a bunch of research today:

- The tests do fail fast; if there is an error in a test then the others are not run and lerna exits early. This is fine for tests (or at least debatable) where if there's a failure you probably want to know asap, but it's undesirable for lint where you should be able to see all lint messages at once and not have to rerun it multiple times. You can prevent this behavior with `lerna run --no-bail test`
- I was wrong in my earlier comment, if you use `--no-bail` correctly then lerna will still ultimately exit 1 if any script failed
- The reason my earlier approach for linting didn't work was due to the promise-based nature of the lint script and this is resolvable by using promises correctly

 ## Related to the publishing problems:

- Personally, I don't think lint errors should cause publishing to fail. Especially to fail silently due to just not making a `dist` directory. Like, ideally we don't have lint errors for our own sake, but if one sneaks in it shouldn't be fatal to a published package. This might be mostly a moot point if we get the CI to fail so we are more confident that lint errors won't happen, but I still don't like it.
- As far as I can tell, the `lint` script in dev-scripts is not actually run during build/publish. Instead, eslint is run during the webpack build, here: https://github.com/google/blockly-samples/blob/master/plugins/dev-scripts/config/webpack.config.js#L95 
    - Therefore, anything that changes just the `lint` script would not affect what actually happens during publishing.
    - We are using a deprecated package to load eslint. According to that package, `failOnError` and `failOnWarning` are both false by default, and we don't set them so they should theoretically be false. So I don't know how lint errors would be causing the build to fail and the `dist` directory to not be created. (In the replacement for that deprecated package, I think `failOnError` is true by default, but we aren't using it, so irrelevant). https://www.npmjs.com/package/eslint-loader#failonerror
    - There is an issue/bug related to this I don't understand: https://github.com/google/blockly-samples/issues/636
        - Prior to this, `emitWarnings` was always true.
        - After this, `emitWarnings` is only true in development mode.
        - I don't know how that achieves what it seems like the goal was: "Fail on lint errors during build but not when running in the development environment." For one thing, just emitting the warnings shouldn't cause failure because the `failOnWarning` should be false, as stated above. For another, it seems like this would do the opposite, where warnings are only emitted during development. So overall this just confuses me.
 - It's unclear why exactly lint errors are causing publish failures. From the above points, it seems like they shouldn't cause the webpack build to fail, and the webpack build is what creates the `dist` directory. However, it definitely does seem like there was some error related to this in July. We don't seem to have extensive debugging information written down anywhere, but here is a related bug https://github.com/google/blockly-samples/issues/804, which mentions https://github.com/google/blockly-samples/pull/803 which says that before this we had lint errors and no dist folder, after fixing them we had a dist folder. Abby also remembers this being the case and looking into it and being pretty confident that it was caused by the lint errors.
 - However, we currently have lint errors that don't seem to be blocking publishing. For example, `block-dynamic-connection` has lint errors (line length is a lint error, not just a warning) and yet it was published last week and has a dist directory. So what changed between July and now? I haven't found an explanation.


## Takeaways

It would be easier to implement changes if we had an agreed-upon end state. Here is my suggestion

- Neither lint warnings nor lint errors should cause publishing to fail (either silently or not)
- Neither lint warnings nor lint errors should cause a development build to fail (i.e., during development, the webpack dev server should not refuse to load your code due to lint problems). Whether or not you are alerted to these (in a non-blocking manner) is up for debate. I don't think it's that important myself as you should run the linter independently before opening a PR but there has to be some reason we currently have it configured to show them in production.
- Lint errors should cause GitHub CI to fail.
- Lint warnings should cause GitHub CI to ??? Ideally, it would cause them to warn, but I think that requires more complex setup because you can't just rely on the exit code, but can look into that later if it's what we want.
- Lint warnings and errors should both cause errors when you run `npm run lint` locally, either on an individual plugin or at the root level.

## Current work

Since the publishing script does not actually run the `lint` script itself, getting GitHub CI to fail is unrelated to whether publishing fails. So we can continue working on the former while we figure out what to do about the latter. Therefore for now I will focus on getting GitHub CI to fail for lint errors. I still believe we should figure out what's going on with publishing though to prevent future errors that are difficult to detect.

**Comment by maribethb** [comment]
What I'm leaning towards right now is just getting rid of our `lint` script entirely and setting `npm run lint` to run `eslint src test` which is pretty much what our script does, just in a more complicated way. 

One possible problem with that is it seems like lerna didn't link the eslint-config properly. When I did `npm list @blockly/eslint-config` it seemed like it was using the local version of it, but when I used the `--print-config` option with eslint it clearly wasn't. Manually running `npm link` on the eslint config worked fine though. So that has the potential to be annoying whenever we are editing the eslint-config, but it's not the end of the world. Where it may get complicated is if we do fail GH CI on lint errors, but fixing the eslint config in the same PR isn't enough since you can't run `npm link` in the CI. I don't know why lerna isn't able to link it though. :/ will keep looking into this to see if maybe i've borked lerna somehow.

Edit: The lerna issue was because the plugins don't have `@blockly/eslint-config` as a devDependency, though they do in fact directly depend on it due to the `eslintConfig` option in the package.json. Adding the package as a devDependency causes lerna to link it as expected, so I'm planning to move forward with this solution.

**Comment by maribethb** [comment]
To follow up on this, Sam says we shouldn't evoke `eslint` directly (as opposed to from node) because if someone uses our script to create a plugin outside of blockly-samples and runs the script, they would get errors if they didn't have eslint installed, and we don't want to install eslint automatically in each plugin because we already have it installed at the root level of blockly-samples. So we don't want to use that approach after all.

But in #982 Sam makes it so that errors cause a non-zero return code from the script we have so that will also work.

We also found that the build script would also always exit with 0. So if the build failed, but tests somehow passed, CI would not complain and you would only know that by reading the logs. That's what's happening during the publish step when publishing continues despite not having a `dist` directory. So that PR also makes the build script report fail if building fails. That means when we try to publish, it will be even more important to do a dry:run in order to detect any build or lint errors. If there are any, then both dry-run and real publish will quit with an error rather than continue. So that PR is doing double duty to make sure when we publish, we are publishing something that builds.
