### ISSUE TITLE
Keyboard nav uses non-public properties in paste

### ISSUE THREAD

**Issue by rachel-fenichel** [RaspberryPiFoundation/blockly-samples#833]
**Category**

 - Plugins

**Component**

keyboard-navigation

**Describe the bug**

The `paste` function directly accesses `Blockly.clipboardXml_`, `Blockly.clipboardSource_`, and `Blockly.clipboardTypeCounts_`.

These were always supposed to be private, and will disappear in the next Blockly release because of the changes in https://github.com/google/blockly/pull/5237

**To Fix**
- Call `Blockly.getClipboardInfo` to get an object containing the xml, source, and type counts.
- Release after the next Blockly release.

**Comment by rachel-fenichel** [comment]
@BeksOmega pointed out that a better solution would be to restructure [paste](https://github.com/google/blockly-samples/blob/master/plugins/keyboard-navigation/src/navigation.js#L1117) to not access the clipboard contents directly. It could instead call `Blockly.paste` or similar.

**Comment by BeksOmega** [comment]
I think the best thing to do here is probably to modify paste in core to return the block if pasting worked (instead of `true`). Then we would be able to easily insert the pasted block where desired.

Sadly changing the return type of `paste` would be a breaking change (but I don't think many people would be affected).

Otherwise. we could create public accessors, but long-term I don't think this is a great idea. Firstly, it increases the size of Blockly's API, which is ehhhh. And secondly, it means we'll have to keep maintaining and updating keyboard nav's paste as the paste in core changes.
